# Generated by Django 4.0.5 on 2022-06-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='desing_average',
            new_name='design_average',
        ),
    ]
